# Generated by Django 4.1.7 on 2023-03-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name": "Универ", "verbose_name_plural": "Универы"},
        ),
        migrations.AddField(
            model_name="university",
            name="image",
            field=models.ImageField(
                default=1, upload_to="image", verbose_name="Картинка"
            ),
            preserve_default=False,
        ),
    ]
